### ISSUE TITLE
Pig_dice_play

### ISSUE THREAD

**Issue by choiwook940** [himchan94/pig_dice#2]
# Description
Play pig_dice game.

## Tasks
- [x] if dice number is 1, reset player's turn score and turn is over.
- [x] if dice number is not 1 and hold, player's turn score is added to total score and turn is over. If not, dice number is added to turn score and roll dice again.
- [x] if a player scores more than 100 points, game stops and return winner!
